export const FETCH_HEROES_REQUEST = 'FETCH_HEROES_REQUEST';
export const FETCH_HEROES_ERROR = 'FETCH_HEROES_ERROR';
export const FETCH_HEROES_SUCESS = 'FETCH_HEROES_SUCESS';

export const FECT_HERO_REQUEST = 'FECT_HERO_REQUEST';
export const FECT_HERO_ERROR = 'FECT_HERO_ERROR';
export const FECT_HERO_SUCESS = 'FECT_HERO_SUCESS';
